"""Add email attribute

Revision ID: 550fb2a060f4
Revises: f09dbd515fc2
Create Date: 2025-03-14 22:31:34.373972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550fb2a060f4'
down_revision = 'f09dbd515fc2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_student_email', ['email'])  # Pass the name as a string

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_email', type_='unique')  # Drop the constraint by name
        batch_op.drop_column('email')

    # ### end Alembic commands ###
